# Generated by Django 3.2 on 2021-04-27 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitterclone', '0002_choice_question'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
