# Generated by Django 3.2 on 2021-04-27 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitterclone', '0003_following_tweets_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
