# Generated by Django 3.2 on 2021-04-28 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitterclone', '0004_user_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='age',
        ),
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_name',
        ),
    ]
