# Generated by Django 3.2 on 2021-04-27 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitterclone', '0004_auto_20210427_0857'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tweets',
            new_name='Tweet',
        ),
    ]
