# Generated by Django 3.2 on 2021-04-29 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitterclone', '0013_auto_20210429_0830'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userfollowing',
            old_name='following_user_id',
            new_name='following_user',
        ),
        migrations.RenameField(
            model_name='userfollowing',
            old_name='user_id',
            new_name='user',
        ),
    ]
