# Generated by Django 3.2 on 2021-04-29 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitterclone', '0014_auto_20210429_0851'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='age',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
