# Generated by Django 3.2 on 2021-04-30 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('twitterclone', '0016_auto_20210430_1101'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userfollowing',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='userfollowing',
            name='unique_followers',
        ),
        migrations.RemoveField(
            model_name='userfollowing',
            name='following_user_id',
        ),
        migrations.RemoveField(
            model_name='userfollowing',
            name='user_id',
        ),
        migrations.AddField(
            model_name='userfollowing',
            name='following_user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='twitterclone.profile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userfollowing',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='followings', to='twitterclone.profile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userfollowing',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
